apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: file-migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      enableServiceLinks: false
      containers:
        - name: migrate
          image: file-migration-automation:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef: {name: app-config}
            - secretRef: {name: app-secrets}
