# Generated by Django 6.1.1 on 2026-09-11 19:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationHealthOverview',
            fields=[
                ('dest_cloud', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('transferred', models.IntegerField()),
                ('permissions_verified', models.IntegerField()),
                ('permissions_failed', models.IntegerField()),
                ('open_security_mismatches', models.IntegerField()),
            ],
            options={
                'db_table': 'migration_health_overview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionMigrationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_cloud', models.CharField(max_length=10)),
                ('permission_status', models.CharField(max_length=30)),
                ('mapping_table_version', models.CharField(max_length=20, null=True)),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'permission_migration_summary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SignOffGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=255)),
                ('mismatch_type', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sign_off_gate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubtreesNeedingFallbackReview',
            fields=[
                ('subtree_path', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('recent_failures', models.IntegerField()),
                ('last_checked', models.DateTimeField()),
            ],
            options={
                'db_table': 'subtrees_needing_fallback_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EffectivePermissionDiff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=255)),
                ('source_access', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list)),
                ('dest_access', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list)),
                ('mismatch_type', models.CharField(choices=[('missing_grant', 'Missing grant'), ('extra_grant', 'Extra grant'), ('inheritance_divergence', 'Inheritance divergence'), ('unresolvable_identity', 'Unresolvable identity')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('policy_version_at_eval', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'effective_permission_diff',
            },
        ),
        migrations.CreateModel(
            name='ShadowSyncStatus',
            fields=[
                ('subtree_path', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('last_sync_completed_at', models.DateTimeField()),
                ('last_sync_lag_seconds', models.PositiveIntegerField()),
                ('pending_change_count', models.PositiveIntegerField()),
                ('consecutive_stable_checks', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'shadow_sync_status',
            },
        ),
        migrations.CreateModel(
            name='CutoverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=1024)),
                ('mode', models.CharField(choices=[('shadow_write', 'Shadow write'), ('hard_freeze', 'Hard freeze')], default='shadow_write', max_length=20)),
                ('max_acceptable_lag_seconds', models.PositiveIntegerField(default=300)),
                ('lag_stability_window_minutes', models.PositiveIntegerField(default=30)),
                ('auto_fallback_enabled', models.BooleanField(default=False)),
                ('auto_fallback_failure_threshold', models.PositiveIntegerField(default=5)),
                ('auto_fallback_window_hours', models.PositiveIntegerField(default=24)),
                ('active', models.BooleanField(default=True)),
                ('fallback_reason', models.TextField(blank=True, null=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cutover_config',
                'indexes': [models.Index(fields=['scope', 'active'], name='cutover_con_scope_683b29_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiffException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('diff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='migration.effectivepermissiondiff')),
            ],
            options={
                'db_table': 'diff_exception',
            },
        ),
        migrations.CreateModel(
            name='LagStabilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtree_path', models.CharField(max_length=1024)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('lag_seconds', models.PositiveIntegerField()),
                ('threshold_seconds', models.PositiveIntegerField()),
                ('passed', models.BooleanField()),
            ],
            options={
                'db_table': 'lag_stability_check',
                'indexes': [models.Index(fields=['subtree_path', 'checked_at'], name='lag_stabili_subtree_c59d1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MigrationFileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.TextField()),
                ('dest_cloud', models.CharField(choices=[('aws', 'AWS'), ('azure', 'Azure'), ('gcp', 'GCP')], max_length=10)),
                ('dest_path', models.TextField()),
                ('transfer_status', models.CharField(choices=[('queued', 'Queued'), ('transferring', 'Transferring'), ('transferred', 'Transferred'), ('transfer_failed', 'Transfer failed')], default='queued', max_length=20)),
                ('transfer_checksum_match', models.BooleanField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('permission_status', models.CharField(choices=[('pending', 'Pending'), ('applying', 'Applying'), ('applied', 'Applied'), ('verified', 'Verified'), ('mapping_review_needed', 'Mapping review needed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('permission_applied_at', models.DateTimeField(blank=True, null=True)),
                ('permission_verified_at', models.DateTimeField(blank=True, null=True)),
                ('mapping_table_version', models.CharField(blank=True, max_length=20, null=True)),
                ('ace_count_source', models.IntegerField(blank=True, null=True)),
                ('ace_count_dest', models.IntegerField(blank=True, null=True)),
                ('ace_diff_detail', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('workflow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'migration_file_status',
                'indexes': [models.Index(fields=['dest_cloud', 'permission_status'], name='migration_f_dest_cl_d59b10_idx'), models.Index(fields=['source_path'], name='migration_f_source__2eb5bb_idx')],
            },
        ),
        migrations.AddField(
            model_name='effectivepermissiondiff',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_diffs', to='migration.migrationfilestatus'),
        ),
        migrations.CreateModel(
            name='SignOffPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_version', models.CharField(max_length=20)),
                ('mismatch_type', models.CharField(choices=[('missing_grant', 'Missing grant'), ('extra_grant', 'Extra grant'), ('inheritance_divergence', 'Inheritance divergence'), ('unresolvable_identity', 'Unresolvable identity')], max_length=30)),
                ('action', models.CharField(choices=[('block', 'Block'), ('require_exception', 'Require exception'), ('log_only', 'Log only')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sign_off_policy',
                'indexes': [models.Index(fields=['mismatch_type', 'active'], name='sign_off_po_mismatc_ccc693_idx')],
            },
        ),
    ]
