# Generated by Django 6.1.1 on 2026-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_create_reporting_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingReviewQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntfs_right', models.CharField(max_length=50)),
                ('object_type', models.CharField(max_length=10)),
                ('confidence', models.CharField(max_length=20)),
                ('mapping_table_version', models.CharField(max_length=20)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mapping_review_queue_entry',
                'constraints': [models.UniqueConstraint(fields=('ntfs_right', 'object_type', 'mapping_table_version'), name='unique_mapping_review_pattern')],
            },
        ),
    ]
