# Generated by Django 6.1.1 on 2026-09-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0003_mappingreviewqueueentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutoverRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=1024)),
                ('mode', models.CharField(choices=[('shadow_write', 'Shadow write'), ('hard_freeze', 'Hard freeze')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('aborted', 'Aborted')], default='in_progress', max_length=20)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('workflow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cutover_run',
                'indexes': [models.Index(fields=['scope', 'status'], name='cutover_run_scope_61f8d9_idx')],
            },
        ),
    ]
