# Generated by Django 6.1.1 on 2026-09-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0004_cutoverrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50)),
                ('subject_key', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alert_log',
                'constraints': [models.UniqueConstraint(fields=('alert_type', 'subject_key'), name='unique_alert_per_subject')],
            },
        ),
    ]
